### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by Eliaxie** [sup3rgiu/PoliDown#10]
installing on Fedora is necessary to run npm as root flagging --unsafe-perm, which is far from ideal.

**Comment by darklamp** [comment]
You mean installing dependencies requires that flag? If so, I couldn't reproduce that on neither manjaro nor ubuntu; installation on both went just fine without any flag.

**Comment by Eliaxie** [comment]
with all prereqs installed the line `npm install` prints out a ton of errors. I tried to uninstall and set it back up but I couldn't reproduce it, prolly because dependencies were not uninstalled. 
The error npm was printing was

> prebuild-install WARN install EACCES: permission denied, access '/root/.npm

and many more which I don't have anymore, unfortunately.
I don't really know if it has anything to do with your .js or just one of your dependencies needs root + flag, just wanted to let ya know.
