### ISSUE TITLE
Error while trying to download

### ISSUE THREAD

**Issue by GDaglio** [sup3rgiu/PoliDown#11]
I run using the following command (the --username argument is omitted obv)
`node polidown.js --videoUrls "https://web.microsoftstream.com/video/5b4d4a6c-a0a8-48d0-8c20-0df9367dc0e9"`
but I get this error:
![Annotazione 2020-03-13 223214](https://user-images.githubusercontent.com/48480895/76660986-90531180-657a-11ea-828c-b56324eb6323.jpg)

**Comment by sup3rgiu** [comment]
Try running `npm install keytar` after `cd` into the PoliDown folder

**Comment by GDaglio** [comment]
Thanks for the help! Anyway, I fixed reinstalling each component
