### ISSUE TITLE
This is not an exact science 

### ISSUE THREAD

**Issue by miticocampo** [sup3rgiu/PoliDown#12]
more than restarting the prompt and setting everything, is it possible for me to do something more?
![poli](https://user-images.githubusercontent.com/16059281/76681773-f67d7a00-65f6-11ea-9005-956eb1bdae30.jpg)

**Comment by sup3rgiu** [comment]
That's really weird.
I've just tried with the same exact video and it's working
![image](https://user-images.githubusercontent.com/7725068/76683065-4e20e300-6601-11ea-92aa-2301a34aa098.png)

You could try to switch `headless: true` to `headless: false` inside polidown.js and see if in the Chrome windows that will opened everything looks fine.

![image](https://user-images.githubusercontent.com/7725068/76683085-7b6d9100-6601-11ea-9c38-a643b081e05c.png)
