### ISSUE TITLE
Unable to open key file data:text/plain

### ISSUE THREAD

**Issue by hamburger1993** [sup3rgiu/PoliDown#15]
Hi, first thanks for your nice tool =).

until the download part everything runs smooth.
But when it starts to use ffmpeg i get this error:

![Unbenannt](https://user-images.githubusercontent.com/2056948/77224532-03eeb300-6b67-11ea-8d13-a712cc0bbd5c.JPG)

Any idear how i can fix it?

**Comment by sup3rgiu** [comment]
Check this:
https://github.com/sup3rgiu/PoliDown/issues/4#issuecomment-597362863

**Comment by hamburger1993** [comment]
Thanks for your response, i downloaden the nightly-build again, but still getting that error. What i have to tell you is that i modified login to work with my organisation. But the login works fine and the download is also okay. 

The cookie and password are also fetched correctly:
"Got required authentication cookies."

**Comment by sup3rgiu** [comment]
Now that you told me this thing about your organization, looking again at your screenshot, seems that the key is invalid (is not a valid base64 string).
For example, look at the issue I linked above to see a correct base64 encoded key.

We could try to fix this. If you have Telegram, contact me there. My username is: @sup3rgiu

**Comment by hamburger1993** [comment]
well i fixed it, simply use this for the future:

file:C:/Users/MyUser/Desktop/protectionKey

It seems that it was not able to parse the key from base64

**Comment by sup3rgiu** [comment]
Oh nice.
I had to use base64 string on Windows because URI file was not working.
I will try again if it worked for you.

Thanks!
