### ISSUE TITLE
Timeout error for days

### ISSUE THREAD

**Issue by miticocampo** [sup3rgiu/PoliDown#18]
I am experiencing this kind of error for days, for single videos and multiple ones.
I cannot download anything anymore
![image](https://user-images.githubusercontent.com/16059281/77675749-a0f98380-6f8d-11ea-8b34-120dc464afc1.png)

**Comment by sup3rgiu** [comment]
Hi,
I just pushed a new update.
Can you try replacing your polidown.js file with the new one?
Let me know!

**Comment by miticocampo** [comment]
![image](https://user-images.githubusercontent.com/16059281/77685469-c55c5c80-6f9b-11ea-93d3-b235a0eb8158.png)

**Comment by alefuma** [comment]
This error seems to happen when you try to download a video with a better quality than the available ones. 
I tried the new .js file and it works, but when I try to download video(s) using the '-q' attribute with a higher value than the maximum (I experienced it using '-q 5' while the video was available in 1280x720). 
Maybe it could help.

**Comment by miticocampo** [comment]
It works fine now
