### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by rostyclav999s** [sup3rgiu/PoliDown#19]
![Screen Shot 2020-03-27 at 20 02 37](https://user-images.githubusercontent.com/54397912/77786388-69123f00-7066-11ea-9cc5-551c46c437d3.png)
When I try to download a video from Microsoft Streams it gives me that error. I'm on Mac OS Catalina. What should I do?

**Comment by sup3rgiu** [comment]
As I can see from your username, you are not a student of Politecnico di Milano (Italy).
Actually, this tool is done to perform autologin for this University.
I can consider adding an option to use default Microsoft login instead of PoliMi login service for those who are not PoliMi students.

**Comment by rostyclav999s** [comment]
OK, thanks

**Comment by mattkerlos** [comment]
Hello I think I'm Having the same error. I'm not a student of Politecnico di Milano (Italy).
![Screenshot (3)]
![Screenshot (3)](https://user-images.githubusercontent.com/40323508/78163440-f85e8e80-747a-11ea-864e-e400dfa78401.png)

**Comment by sup3rgiu** [comment]
@rostyclav999s 
https://github.com/sup3rgiu/MStreamDownloader
