### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by Christiandd** [sup3rgiu/PoliDown#2]
Sometimes may appear "timeouterror" after "Filling in servizi online". It is probably caused by the PoliMi warning "The password will expire in.." and can be easily solved changing the password.

**Comment by sup3rgiu** [comment]
You are right.
However I can bypass this warning. Will push a new commit soon

**Comment by sup3rgiu** [comment]
Fixed with commit e017cd1994425094c1d3e8986581d342ada0b559
