### ISSUE TITLE
Hello! Can you add support for non students of Politecnico di Milano (Italy)??

### ISSUE THREAD

**Issue by mattkerlos** [sup3rgiu/PoliDown#21]
**Firstly** Thank you so much for your effort and generosity.
Can you add support for students **outside of Politecnico di Milano?**
Thanks!
![Screenshot (3)](https://user-images.githubusercontent.com/40323508/78163548-20e68880-747b-11ea-949b-fb43d525e40b.png)

**Comment by sup3rgiu** [comment]
Hi, sure :)

https://github.com/sup3rgiu/MStreamDownloader

For future issues, post them in that repository

**Comment by mattkerlos** [comment]
Thanks so Much!
