### ISSUE TITLE
Error! How I can resolve it?

### ISSUE THREAD

**Issue by IlariaAnita** [sup3rgiu/PoliDown#27]
[crypto @ 00000251742672c0] Unable to open resource: aaudio_segments/Fragments(aac_eng_1_60_1_1=2767360000,format=m3u8-aapl)
[hls @ 000002517425de40] Failed to open segment 46 of playlist 0
[hls @ 000002517425de40] Error when loading first segment 'aaudio_segments/Fragments(aac_eng_1_60_1_1=0,format=m3u8-aapl)'
audio_tmp.m3u8: Invalid data found when processing input
(node:23128) UnhandledPromiseRejectionWarning: Error:  Command failed: ffmpeg -protocol_whitelist file,http,https,tcp,tls,crypto,data -allowed_extensions ALL -i audio_tmp.m3u8 -protocol_whitelist file,http,https,tcp,tls,crypto,data -allowed_extensions ALL -i video_tmp.m3u8 -async 1 -c copy -bsf:a aac_adtstoasc -n "..\..\videos\Lesson 26_04_2020 - FRIGO CARLO ALBINO  083148-RIABILITAZIONE MOTORIA [M.S.] (712476).mp4"
    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at downloadVideo (C:\Projects\PoliDown\polidown.js:426:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:23128) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23128) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by sup3rgiu** [comment]
Hi, can you try adding the `-o` parameter to define a custom output directory?

For example:
`node polidown.js -u CODICEPERSONA -v "https://web.microsoftstream.com/video/VIDEO-1" -o "/my/output/path/here"`

**Comment by sup3rgiu** [comment]
This is a bug of the beta version of ffmpeg.
Please download the stable version 4.2.2:
https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-4.2.2-win64-static.zip
