### ISSUE TITLE
Downloading just the first URL in a file on OSX (and maybe Linux)

### ISSUE THREAD

**Issue by stefanomaxenti** [sup3rgiu/PoliDown#28]
TXT files containing more URLs can't correctly be parsed on OSX (and maybe Linux).

The reason is linked to this function:
function readFileToArray(path) {
    path = path.substr(1,path.length-2);
    return fs.readFileSync(path).toString('utf-8').split('**\r**\n');
}
Files created on Linux and OSX don't use \r\n but just \n. On Unix, it is necessary to remove only \n. I assume Windows version don't have this problem.

**Comment by peppelongo96** [comment]
This function was added by last my commit. Thanks for notifying. I'll do new pull request to fix it :)
