### ISSUE TITLE
Download multiple videos

### ISSUE THREAD

**Issue by Christiandd** [sup3rgiu/PoliDown#3]
When you try to download multiple videos from the same course it save only the first one. To solve this you could add a simple variable that increases in the for at the end of the name of the output file.

**Comment by sup3rgiu** [comment]
I'm already doing this (with the release v1.1.0).
If a file with the same name already exists, it will renamed adding a timestamp in the filename.
Did you have this problem with the release v1.1.0 too?

**Comment by sup3rgiu** [comment]
Closed for inactivity
