### ISSUE TITLE
Automatic maximum resolution

### ISSUE THREAD

**Issue by ilMan2** [sup3rgiu/PoliDown#38]
HI everyone,
i'm using PoliDown and it's amazing! However i noticed that it ask for every video the resolution at witch it has to be download. It is possible to implement something that automatically select the best available resolution? In that way it will be possible to add a long list of video without being in front of pc and let downloads run during night.

Thanks a lot for that tool
Bye

**Comment by sup3rgiu** [comment]
Hi,
you can use the `-q` flag in order to define the quality.
For example, `-q 5` will download the videos at the maximum resolution available.
