### ISSUE TITLE
problem afterdownload

### ISSUE THREAD

**Issue by lucio97** [sup3rgiu/PoliDown#4]
hi, the script give me this error when i try to download a video. i think it have something to do with the parsing process of the downloaded pieces.

i edited the const argv = yargs.options (lines 13-18), adding my codice persona, password and output after default:, in this way the only arg is the --videoUrls. i don't think this have anything to do w/ the problem above.
with the older version, everything is fine.

![2020-03-10 (1)](https://user-images.githubusercontent.com/9356159/76365519-c77db480-6327-11ea-9c64-fd101bc2d246.png)

**Comment by sup3rgiu** [comment]
hi,
please, use the nightly build for ffmpeg: https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-20200309-608b8a8-win64-static.zip

I'm trying to find a better way to parse the protection key on Windows

**Comment by lucio97** [comment]
i did it, now it give me a new error lol

![2020-03-11](https://user-images.githubusercontent.com/9356159/76370917-be491380-6338-11ea-84a8-0e3ad4540309.png)

**Comment by sup3rgiu** [comment]
Will fix it soon.
This is because you specified an absolute path for the outputDirectory.
Try `--outputDirectory "videos"` or omitting it completely. It should create the output directory inside the script directory

**Comment by lucio97** [comment]
Okok I’ll try later and let you know 💪🏻

**Comment by lucio97** [comment]
no more red errors, but still not working. (i've had two video urls in queue)
![2020-03-11 (1)](https://user-images.githubusercontent.com/9356159/76445667-111cdc80-63c6-11ea-8702-5efdd91c7251.png)

**Comment by sup3rgiu** [comment]
Can you paste here the exact command that you are using to download two videos? (omit username and password of course)

**Comment by lucio97** [comment]
node .\polidown.js --outputDirectory "videos" --videoUrls "https://web.microsoftstream.com/video/289b7a7a-e59b-4b31-8d06-29e007611a8c" \ "https://web.microsoftstream.com/video/4326e37e-b446-4ddc-879c-f79479a4a5ad"

**Comment by sup3rgiu** [comment]
Sorry, the `\` character is usually used to write a command on more lines to make it more readable in the documentation.
It should not be used in the actual command.

Correct command is:
`node .\polidown.js --outputDirectory "videos" --videoUrls "https://web.microsoftstream.com/video/289b7a7a-e59b-4b31-8d06-29e007611a8c" "https://web.microsoftstream.com/video/4326e37e-b446-4ddc-879c-f79479a4a5ad"`

**Comment by lucio97** [comment]
oh jeez, i completely forgot about that lol. i don't know why I didn't think of that

mi sento maleeeee haahah
