### ISSUE TITLE
Video not downloaded

### ISSUE THREAD

**Issue by MudyAbou** [sup3rgiu/PoliDown#41]
![Immagine 2020-09-18 114014](https://user-images.githubusercontent.com/70200338/93583266-e7132b00-f9a3-11ea-9cbf-10edb1d5e8f4.jpg)
Hello,

It give me this error i don't understand how to solve it. Can anyone please help me ?

**Comment by lucio97** [comment]
This tool work only for Microsoft streams.
For Webex, there is a download button on the recorded lesson page.

**Comment by sup3rgiu** [comment]
For WebEx videos you should use this: https://github.com/sup3rgiu/PoliWebex

Or this browser extension https://github.com/jacopo-j/WebXDownloader

**Comment by MudyAbou** [comment]
Thanks a lot!
