### ISSUE TITLE
remove "nightly build" option from PREREQS

### ISSUE THREAD

**Issue by AmadeusZhang** [sup3rgiu/PoliDown#43]
ffmpeg.zeranoe.com closed since Sep 18, 2020.

![image](https://user-images.githubusercontent.com/39902414/93892175-8578f680-fcec-11ea-943f-85a24fb6ead0.png)

**Comment by sup3rgiu** [comment]
Thanks for the update! Done in https://github.com/sup3rgiu/PoliDown/commit/91770cc40c358a4274b6283391acc344688c543a
