### ISSUE TITLE
Problem with file video

### ISSUE THREAD

**Issue by filo98filo98** [sup3rgiu/PoliDown#8]
![WhatsApp Image 2020-03-12 at 23 10 40](https://user-images.githubusercontent.com/62121293/76572491-8669d980-64ba-11ea-87e5-8435739b12c0.jpeg)

After selecting the video quality, the download starts;
After downloading all the files I get this message and in my folder videos I have only a lot of small file, but not an mp4 video

**Comment by sup3rgiu** [comment]
Use the nightly build of ffmpeg:
https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-20200309-608b8a8-win64-static.zip

**Comment by filo98filo98** [comment]
solved, thanks
