### ISSUE TITLE
Add option to opt-out of using system keyring

### ISSUE THREAD

**Issue by Leosxe** [sup3rgiu/PoliDown#9]
After  #5 (commit e017cd1) I had some problems on Linux; as reported in this issue (https://github.com/Foundry376/Mailspring/issues/681) and other, node-keytar works only with libsecret, and libsecret only works with gnome-keyring. Since I don't use gnome, I think it would be better to have an option not to use it, much like there is a way to not use it if X11 is not installed. I have absolutely no problem with version before commit e017cd1.

I suggest maybe having a command line option to explicitly say not to use the keyring.

**Comment by sup3rgiu** [comment]
I will consider this option for sure!

With the current release, it gives you a fatal error or detects your system as one without X11?

Because the try-catch block should detect all the problems with keytar, but always prints "X11 message"

**Comment by lucio97** [comment]
+1 for this one, i would like to have the choice to use the keyring or not.
with the new release, the program automatically save it to the keyring

**Comment by Leosxe** [comment]
I had this message printed 
``** Message: 13:21:34.812: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
``
but now I can't replicate this. I still get this message, but it used to block the program, now it prints the error and keeps working like usual.

**Comment by sup3rgiu** [comment]
Added boolean flag `-k` to avoid keyring usage.
commit 97f47c84814cf6a00ba05b94f58eac31cea323da

Let me know if this solve your problem

**Comment by sup3rgiu** [comment]
I'm closing this issue because it has been inactive for a few months.
